import { type Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types src/libs/appwrite/types`.

export type Category = Models.Row & {
    title: string;
    enabled: boolean;
    templates: Template[];
    icon: string | null;
}

export type Template = Models.Row & {
    category: Category;
    title: string | null;
    prompt: string;
    previewFileId: string | null;
    function: string;
}

export type Creation = Models.Row & {
    executions: CreationExecution[];
    originalFileId: string;
    outputFileId: string | null;
    status: string;
}

export type CreationExecution = Models.Row & {
    creation: Creation;
}

export type SupportRequests = Models.Row & {
    category: string;
    email: string | null;
    message: string;
    notify_user: boolean;
}

export type Feedbacks = Models.Row & {
    rating: number;
    message: string | null;
    table_name: string | null;
    table_id: string | null;
    email: string | null;
    user_id: string | null;
}
